"""Real text-layer extracts from the user's CommScope sample PDF.

These are the exact strings PyMuPDF returns from page.get_text(). Used to
verify the parser without depending on the actual PDF being present.
"""

PAGE_1_SIMPLE = (
    "COMMERCIAL INVOICE\nITN Number\nCommercial Invoice Number\n9010114526\n"
    "Commercial Invoice Date\n19 JAN 2026\nPage : 1 of 1\nCreated By  : Djamay\n"
    "Customer VAT :\nIncoterms\nFCA COMMSCOPE FACTORY\nFreight Forwarder\n22310386\n"
    "Shipment Number\nNL\nShip From Country\nLetter Of Credit\nOrder\nOrder \nItem\n"
    "Material ID/Customer Material \nID\nMaterial Description\nQty Shipped\nUOM\n"
    "Unit \nPrice\nU/P\nNet Amount\nFreight\nVAT Amount\nMaterial Total\nSurcharge\n"
    "Invoice Total\nInv. Currency  \n0.00\n0.00\n24,374.93\n0.00\n24,374.93\nUSD\n"
    "Sold To : 1012320\nGULF APPLICATION COMPANY GAPP\n3074 AL AMIR MUHAMMAD IBN ABDULAZIZ\n"
    "AL ULAYA UNIT NO 55\n12213 RIYADH\nSAUDI ARABIA\n"
    "Ship To : 52571\nGULF APPLICATION COMPANY GAPP\n3074 AL AMIR MUHAMMAD IBN ABDULAZIZ\n"
    "ROAD AL ULAYA UNIT NO 55\n12213 RIYADH\nSAUDI ARABIA\n"
    "Freight Forwarder  :\nNotify Party :\nCOMMSCOPE EMEA LTD.\nARSENAAL 2\n"
    "3905 NN  VEENENDAAL\nNETHERLANDS\nShip From  :\n"
    "Exporter\nCommscope EMEA Limited\nCorke Abbey Bray\nDublin\nIreland\nwww.commscope.com\n"
    "Terms and Conditions :  https://www.commscope.com/About-Us/Terms/ \n"
    "PC\n97.49972\n250\nPC\n360G2 Cartridge 12-LC-SM-BL-Pigtails\n"
    "760109496\n000060\n6116852\n24,374.93\n"
    "Purchase Order : 5500001219\nPurchase Order Item : 6\n"
    "ECCN No: ECL99\nLicense No: NLR\nCountry Of Origin: IN\nHTS Code : 85367000\n"
    "Preference : NO\n360G2  Singlemode  Fiber Cassette 12 LC, with pigtails, iPatch Ready\n"
    "This tariff classification is only applicable in the country of export and the importer "
    "remains responsible for a correct classification based upon the legal obligations of "
    "the country of import. \n \n"
)

PAGE_4_MULTI_WITH_WRAP = (
    "COMMERCIAL INVOICE\nITN Number\nCommercial Invoice Number\n9010127555\n"
    "Commercial Invoice Date\n26 FEB 2026\nPage : 1 of 1\nCreated By  : Mike\n"
    "Customer VAT :\nIncoterms\nFCA CommScope Factory\nFreight Forwarder\n22341659\n"
    "Shipment Number\nNL\nShip From Country\nLetter Of Credit\nOrder\nOrder \nItem\n"
    "Material ID/Customer Material \nID\nMaterial Description\nQty Shipped\nUOM\n"
    "Unit \nPrice\nU/P\nNet Amount\nFreight\nVAT Amount\nMaterial Total\nSurcharge\n"
    "Invoice Total\nInv. Currency  \n0.00\n0.00\n6,664.69\n0.00\n6,664.69\nUSD\n"
    "Sold To : 1012320\nGULF APPLICATION COMPANY GAPP\n3074 AL AMIR MUHAMMAD IBN ABDULAZIZ\n"
    "AL ULAYA UNIT NO 55\n12213 RIYADH\nSAUDI ARABIA\n"
    "Ship To : 52571\nGULF APPLICATION COMPANY GAPP\n3074 AL AMIR MUHAMMAD IBN ABDULAZIZ\n"
    "ROAD AL ULAYA UNIT NO 55\n12213 RIYADH\nSAUDI ARABIA\n"
    "Freight Forwarder  :\nNotify Party :\nCOMMSCOPE EMEA LTD.\nARSENAAL 2\n"
    "3905 NN  VEENENDAAL\nNETHERLANDS\nShip From  :\n"
    "Exporter\nCommscope EMEA Limited\nCorke Abbey Bray\nDublin\nIreland\nwww.commscope.com\n"
    "Terms and Conditions :  https://www.commscope.com/About-Us/Terms/\n"
    "EA\n6.28261\n180.000\nEA\nNPC CAT 6, UTP, LSZH, WT, 5M\n"
    "NPC06UZDB-WT005M\n000050\n6184628\n1,130.87\n"
    "Purchase Order : 5500001378\nPurchase Order Item : 5\n"
    "ECCN No: ECL99\nLicense No: NLR\nCountry Of Origin: TN\nHTS Code : 85444210\n"
    "Preference : NO\nNPC RJ45 Patch Cord, category 6, U/UTP, LSZH, white, 5m\n"
    "EA\n9.90860\n100.000\nEA\nNPC CAT 6, UTP, LSZH, WT, 10M\n"
    "NPC06UZDB-WT010M\n000060\n6184628\n990.86\n"
    "Purchase Order : 5500001378\nPurchase Order Item : 6\n"
    "ECCN No: ECL99\nLicense No: NLR\nCountry Of Origin: TN\nHTS Code : 85444210\n"
    "Preference : NO\nNPC RJ45 Patch Cord, category 6, U/UTP, LSZH, white, 10m\n"
    "PC\n19.83825\n229\nPC\nJUMPER,LSZH,LS,1.6MM,DPLX,LC/\nLC,AQ,FT010\n"
    "FFXLCLC42-MXF010\n000070\n6184628\n4,542.96\n"
    "Purchase Order : 5500001378\nPurchase Order Item : 7\n"
    "ECCN No: ECL99\nLicense No: NLR\nCountry Of Origin: CN\nHTS Code : 85447000\n"
    "Preference : NO\nOM4 LC to LC, Fiber Patch Cord, 1.6 mm Duplex, Low Smoke Zero Halogen "
    "(LSZH), Aqua, 10ft\n"
    "This tariff classification is only applicable in the country of export and the importer "
    "remains responsible for a correct classification based upon the legal obligations of "
    "the country of import. \n \n"
)
